### ISSUE TITLE
Privacy and data

### ISSUE THREAD

**Issue by GuidoPenta** [cesconix/pentametro#3]
Yo!
I think you should include an additional disclaimer about the data included within the CV (for example, it would be preferable to have a CV uploaded without personal data such as phone, email, address or other relevant information).
Where does the data go? This is important information in my opinion that needs to be made explicit!

**Comment by cesconix** [comment]
Thanks for pointing that out! I’ve released an update with a disclaimer and a Privacy Policy. When users click "Scegli file", a modal pops up where they can either accept or cancel. If they accept, the process continues. Hope that's okay!

As always, feedback is welcome!
